<?php
$v_params = $this->getParams();
$vetor = $v_params['vetor'];

$controle = $_REQUEST['controle'];

include_once 'includes/head.php';
?>

</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
    <?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Relat&oacute;rios</h1>
        
        <?php if (isset($_GET['msg']) != "") { ?>
		     <div id="mensagem" style="display:block;">
		        <?php //echo strtoupper($mensagem);
		        		include_once 'lib/Mensagens.php';
					$msg = new Mensagens($_GET['msg']);
		        ?>
		     </div>
        <?php } ?>
        
        <section id="opcoes">
            <div id="filtros">
                <form name="filtro" method="post">
                    <select name="status" id="status">
                        <option value="1" selected="selected">Status:</option>
                        <option value="1">Ativo</option>
                        <option value="2">Inativo</option>
                    </select>
                    &nbsp;&nbsp;&nbsp;
                    
                    <?php
					 include_once 'controllers/SelectorController.php';
					 $seletor = new SeletorController();
					 // seletor de filiais
					 if ($_SESSION['hashid'] == "superadmin") {
					 	echo $seletor->seletores(11,$_SESSION['idUsuario']);
					 } else 
					 if ($_SESSION['hashid'] == "cliente") {
					 	echo $seletor->seletores(13,$_SESSION['idUsuario']);
					 }
				?>
                    &nbsp;&nbsp;&nbsp;
                    
                    <?php
					 // seletor de clientes
					 if ($_SESSION['hashid'] == "gerentefilial" || $_SESSION['hashid'] == "superadmin") {
					 	$seletor = new SeletorController();
					 	echo $seletor->seletores(12,$_SESSION['idFilial']);
					 }
				?>
                    &nbsp;&nbsp;
                    
                    <input type='hidden' name='filtro' value='1'>
                    <input type='hidden' name='controle' value='Arquivo'>
				<input type='hidden' name='acao' value='listar'>
                    <input type="submit" value="Filtrar" />
                </form>
            </div>
		<?php if ($_SESSION['hashid'] == "gerentefilial" || $_SESSION['hashid'] == "desenvolvedor") { ?>
                <a id="novo" href='?controle=<?php echo $controle; ?>&acao=manter' class='icoNovo'>Adicionar um novo arquivo</a>
		<?php } ?>
        </section>
        <div class="clear"></div>
	   
			
        <table style="width:100%;" id="table" class="sortable">
			<thead>	
				<tr>
					<th>Id</th>
					<th>Descri&ccedil;&atilde;o</th>
					<th>Data Vencimento</th>
					<th>Data Exclus&atilde;o</th>
					<th>Publicado em</th>
					<th class="nosort"></th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach($vetor AS $item) { ?>
					<tr>
						<td><?php echo $item->getPkArquivo(); ?></td>
						<td><?php echo $item->getDescricao(); ?></td>
						
                        <td><?php echo implode("/", array_reverse(explode("-",$item->getDtVence()))); ?></td>
						<td><?php echo implode("/", array_reverse(explode("-",$item->getDtExclusao()))); ?></td>
						<td><?php echo implode("/", array_reverse(explode("-",$item->getDtInclusao()))); ?></td>
					
					<?php if ($_SESSION['hashid'] == "gerentefilial" || $_SESSION['hashid'] == "desenvolvedor") { ?>
						<td>
                            	<?php if ($item->getArquivoStatus() == 2) { ?>
                            		<a href="?controle=<?php echo $controle; ?>&acao=ativar&id=<?php echo $item->getPkArquivo()?>" class="icoPublicar linkOpcoes">Publicar</a>
                            	<?php } else if ($item->getArquivoStatus() == 1) { ?>
                            		<a href="?controle=<?php echo $controle; ?>&acao=ativar&id=<?php echo $item->getPkArquivo()?>" class="icoDespublicar linkOpcoes">Despublicar</a>
                            	<?php } ?>
							
							<a href='?controle=<?php echo $controle; ?>&acao=manter&id=<?php echo $item->getPkArquivo()?>' class='icoEditar linkOpcoes'>Editar</a>
							<a href='?controle=<?php echo $controle; ?>&acao=apagar&id=<?php echo $item->getPkArquivo()?>' class='icoExcluir linkOpcoes'>Excluir</a>
						
						<?php if ($item->getTipo() == "pdf") { ?>
							<a href='?controle=<?php echo $controle; ?>&acao=ver&id=<?php echo $item->getPkArquivo()?>' class='icoVerArquivo linkOpcoes' target='_blank'>Ver</a>
						<?php } ?>
						</td>
					<?php } else { ?>
						<td>
						<?php if ($item->getTipo() == "pdf") { ?>
							<a href='?controle=<?php echo $controle; ?>&acao=ver&id=<?php echo $item->getPkArquivo()?>' class='icoVerArquivo linkOpcoes' target='_blank'>Ver</a>
						<?php } ?>
							<a href='?controle=<?php echo $controle; ?>&acao=baixar&id=<?php echo $item->getPkArquivo()?>' class='icoBaixarArquivo linkOpcoes'>Baixar</a>
						</td>
					<?php } ?>
					</tr>
				<?php } ?>
			</tbody>
			</table>

			<!-- Paginação -->
			<?php include_once 'includes/paginacao.php'; ?>
	</article>
</body>
</html>