<?php
$v_params = $this->getParams();
$vetor = $v_params['vetor'];

$controle = $_REQUEST['controle'];

include_once 'includes/head.php';
?>

</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
	<?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Cidade</h1>
        <?php if (isset($_GET['msg']) != "") { ?>
		     <div id="mensagem" style="display:block;">
		        <?php //echo strtoupper($mensagem);
		        		include_once 'lib/Mensagens.php';
					$msg = new Mensagens($_GET['msg']);
		        ?>
		     </div>
		<?php } ?>
		
        <section id="opcoes">
            <div id="filtros">
                <form name="filtro" method="post">
                    <label for="cidade">Cidade:</label>
                    <input type="text" name="cidade" id="cidade" value="" />
                    
                    <?php include_once 'controllers/SelectorController.php';
					 $seletor = new SeletorController();
					 echo $seletor->seletores(15,$_SESSION['idUsuario']);
				?>
                    
                    <input type='hidden' name='controle' value='Cidade'>
				<input type='hidden' name='acao' value='listar'>
                    <input type="submit" value="Filtrar" />
                </form>
            </div>
            <?php if ($_SESSION['adicionar'] == 1) { ?>
                <a id="novo" href='?controle=<?php echo $controle; ?>&acao=manter' class='icoNovo'>Adicionar uma nova cidade</a>
            <?php } ?>
        </section>
        <div class="clear"></div>
			
			
        <table style="width:100%;" id="table" class="sortable">
			<thead>	
				<tr>
					<th>Id</th>
					<th>Cidade</th>
					<th>Estado</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach($vetor AS $item) { ?>
					<tr>
						<td><?php echo $item->getPkCidade(); ?></td>
						<td><?php echo $item->getCidade(); ?></td>
						<td><?php echo $item->getEstado(); ?></td>
						<td>
							<?php if ($_SESSION['editar'] == 1) { ?><a href='?controle=<?php echo $controle; ?>&acao=manter&id=<?php echo $item->getPkCidade()?>' class='icoEditar linkOpcoes'>Editar</a><?php } ?>
							<?php if ($_SESSION['excluir'] == 1) { ?><a href='?controle=<?php echo $controle; ?>&acao=apagar&id=<?php echo $item->getPkCidade()?>' class='icoExcluir linkOpcoes'>Excluir</a><?php } ?>
						</td>
					</tr>
				<?php } ?>
			</tbody>
		</table>
		<!-- Paginação -->
		<?php include_once 'includes/paginacao.php'; ?>
	</article>
</body>
</html>