<?php
$v_params = $this->getParams();
$vetor = $v_params['vetor'];

$controle = $_REQUEST['controle'];

include_once 'includes/head.php';
?>
<script type="text/javascript">
 jQuery(document).ready(function($) {
   $("#cnpj").mask("99.999.999/9999-99");
});
</script>
</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
    <?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Clientes</h1>
        <?php if (isset($_GET['msg']) != "") { ?>
	     <div id="mensagem" style="display:block;">
	        <?php //echo strtoupper($mensagem);
	        		include_once 'lib/Mensagens.php';
				$msg = new Mensagens($_GET['msg']);
	        ?>
	     </div>
	   <?php } ?>
		
        <section id="opcoes">
            <div id="filtros">
                <form name="filtro" method="post">
                    <select name="status" id="status">
                        <option value="1" selected="selected">Status:</option>
                        <option value="1">Ativo</option>
                        <option value="2">Inativo</option>
                    </select>
                    
                    <label for="nome">Nome:</label>
                    <input type="text" name="nome" id="nome" value="" />
                    
                    <label for="cnpj">CNPJ:</label>
                    <input type="text" name="cnpj" id="cnpj" value="" />
                    
                    <label for="contrato">Contrato:</label>
                    <input type="text" name="contrato" id="contrato" value="" />
                    
                    <input type='hidden' name='controle' value='Cliente' />
                    <input type='hidden' name='acao' value='listar' />
                    <input type="submit" value="Filtrar" />
                </form>
            </div>
            <?php if ($_SESSION['hashid'] == "superadmin" || $_SESSION['hashid'] == "desenvolvedor") { ?>
                <a id="novo" href='?controle=<?php echo $controle; ?>&acao=manter' class='icoNovo'>Adicionar um novo cliente</a>
            <?php } ?>
        </section>
        <div class="clear"></div>
			
			
        <table style="width:100%;" id="table" class="sortable">
			<thead>	
				<tr>
					<th>Id</th>
					<th>No. Contrato</th>
					<th>Nome Fantasia</th>
					<th>Razão Social</th>
					<th>CNPJ</th>
					<th>Cidade</th>
				<?php if ($_SESSION['hashid'] == "superadmin" || $_SESSION['hashid'] == "desenvolvedor") { ?>
					<th class="nosort"></th>
				<?php } ?>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach($vetor AS $item) { ?>
					<tr>
						<td><?php echo $item->getPkCliente(); ?></td>
						<td><?php echo $item->getContrato(); ?></td>
						<td><?php echo $item->getNomeFantasia(); ?></td>
						<td><?php echo $item->getRazaoSocial(); ?></td>
						<td><?php echo $item->getCnpj(); ?></td>
						<td><?php echo $item->getNomeCidade(); ?></td>
					<?php if ($_SESSION['hashid'] == "superadmin" || $_SESSION['hashid'] == "desenvolvedor") { ?>
						<td>
                            	<?php if ($item->getClienteStatus() == 0) { ?>
                            		<a href="#" class="icoPublicar linkOpcoes">Publicar</a>
                            	<?php } else if ($item->getClienteStatus() == 1) { ?>
                            		<a href="#" class="icoDespublicar linkOpcoes">Despublicar</a>
                            	<?php } ?>
							<a href='?controle=<?php echo $controle; ?>&acao=manter&id=<?php echo $item->getPkCliente()?>' class='icoEditar linkOpcoes'>Editar</a>
							<a href='?controle=<?php echo $controle; ?>&acao=apagar&id=<?php echo $item->getPkCliente()?>' class='icoExcluir linkOpcoes'>Excluir</a>
						</td>
					<?php } ?>
					</tr>
				<?php } ?>
			</tbody>
		</table>
        <!-- Paginação -->
        <?php include_once 'includes/paginacao.php'; ?>
	</article>
</body>
</html>