<?php
$v_params = $this->getParams();
$vetor = $v_params['vetor'];

$controle = $_REQUEST['controle'];

include_once 'includes/head.php';
?>

</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
	<?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Fotos</h1>
        <?php if (isset($_GET['msg']) != "") { ?>
		     <div id="mensagem" style="display:block;">
		        <?php //echo strtoupper($mensagem);
		        		include_once 'lib/Mensagens.php';
					$msg = new Mensagens($_GET['msg']);
		        ?>
		     </div>
		<?php } ?>
			
			<div id="barraOpcoes">
				<div id="menuOpcoes">
					<?php if ($_SESSION['hashid'] == "gerentefilial" || $_SESSION['hashid'] == "desenvolvedor") { ?>
						<a href='?controle=<?php echo $controle; ?>&acao=manter' class='icoNovo'>Adicionar</a>&nbsp;|&nbsp;
					<?php } ?>
				</div>
				
				<div id="barraFiltros">
					Filtrar:
				</div>
			</div>
			
			<table width="100%" id="table" class="sortable">
			<thead>	
				<tr>
					<?php if ($_SESSION['hashid'] == "gerentefilial" || $_SESSION['hashid'] == "desenvolvedor") { ?>
						<th class="nosort" style="width: 120px;"></th>
					<?php } ?>
					<th style="width: 30px;">Id</th>
					<th>Loja</th>
					<th>Coordenador</th>
					<th>Promotor</th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach($vetor AS $item) { ?>
					<tr>
					<?php if ($_SESSION['hashid'] == "gerentefilial" || $_SESSION['hashid'] == "desenvolvedor") { ?>
						<td align="center" width="120">
							<a href='?controle=<?php echo $controle; ?>&acao=manter&id=<?php echo $item->getPkFoto()?>' class='icoEditar linkOpcoes'>Editar</a>&nbsp;
							<a href='?controle=<?php echo $controle; ?>&acao=apagar&id=<?php echo $item->getPkFoto()?>' class='icoExcluir linkOpcoes'>Excluir</a>
						
						<?php if ($item->getFotoStatus() == 1) { ?>
							<a href='?controle=<?php echo $controle; ?>&acao=ativar&id=<?php echo $item->getPkFoto()?>' class='icoDespublicar linkOpcoes'>Publicar</a>
						<?php } else if ($item->getFotoStatus() == 0) { ?>
							<a href='?controle=<?php echo $controle; ?>&acao=ativar&id=<?php echo $item->getPkFoto()?>' class='icoPublicar linkOpcoes'>Publicar</a>
						<?php } ?>
						</td>
					<?php } ?>
						<td><?php echo $item->getPkFoto(); ?></td>
						<td><?php echo $item->getLoja(); ?></td>
						<td><?php echo $item->getCoordenador(); ?></td>
						<td><?php echo $item->getPromotor(); ?></td>
					</tr>
				<?php } ?>
			</tbody>
			</table>

			<!-- Paginação -->
			<?php include_once 'includes/paginacao.php'; ?>
	</article>
</body>
</html>