<?php
$v_params = $this->getParams();
$objeto = $v_params['objeto'];

include_once 'includes/head.php';
?>
<script type="text/javascript">
 jQuery(document).ready(function($) {
   $("#telefone").mask("(99)9999-9999");
   $("#cpf").mask("999.999.999-99");
});

// jQuery(document).ready(function($) {
	// $("p").hide();
	// $('#btSalvar').click(function() {
		// //desabilitando o submit do form
		// $("form").submit(function () { return false; });
		// //atribuindo o valor do campo
		// var sEmail	= $("#email").val();
		// // filtros
		// var emailFilter=/^.+@.+\..{2,}$/;
		// var illegalChars= /[\(\)\<\>\,\;\:\\\/\"\[\]]/
		// // condição
		// if (!(emailFilter.test(sEmail))||sEmail.match(illegalChars)) {
			// $("p").show().removeClass("ok").addClass("erro")
			// .text('Por favor, informe um email válido.');
		// } else {
			// $("p").show().addClass("ok")
			// .text('Email informado está correto!')
		// }
	// });
	// $('#email').focus(function(){
		// $("p.erro").hide();
	// });
// });
</script>
</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
	<?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Usu&aacute;rio</h1>
        <?php if (isset($_GET['msg']) != "") { ?>
		     <div id="mensagem" style="display:block;">
		        <?php 
  		            include_once 'lib/Mensagens.php';
					$msg = new Mensagens($_GET['msg']);
		        ?>
		     </div>
		<?php } ?>
			
			<div id="formulario">
				
				<form id="form" method="post">
					
					<label for="id">Id:</label>
					<input type="text" name="id" size="5" id="id" value="<?php echo $objeto->getPkUsuario()?>" disabled="disabled" />
					
					<label for="perfil">Nome:</label>
					<input type="text" name="nome" id="nome" value="<?php echo $objeto->getNome()?>" required />

					<br />
					<label for="cargo">Cargo:</label>
					<input type="text" name="cargo" id="cargo" value="<?php echo $objeto->getCargo()?>" required />
					
					<br />
					<label for="telefone">Telefone:</label>
					<input type="text" name="telefone" id="telefone" value="<?php echo $objeto->getTelefone()?>" required />
					
					<br />
					<label for="email">E-mail:</label>
					<input type="text" name="email" id="email" value="<?php echo $objeto->getEmail()?>" required />
					<p></p>
					<br />
					<label for="login">Login:</label>
					<input type="text" name="login" id="login" value="<?php echo $objeto->getLogin()?>" required />
					
					<br />
					<label for="senha">Senha:</label>
					<input type="password" name="senha" id="senha" value="<?php echo $objeto->getSenha()?>" required />
					
					<br />
					<label for="cpf">Cpf:</label>
					<input type="text" name="cpf" id="cpf" value="<?php echo $objeto->getCpf()?>" required />
					
					<!-- <br />
					<label for="status">Status:</label>
					<input type="text" name="status" id="status" value="<?php echo $objeto->getUsuarioStatus()?>" required /> -->
					
					<label for="status">Status:</label>
					<select name="status">
						<option value="-1" selected="selected">Selecione:</option>
						<option value="1" <?php if ($objeto->getUsuarioStatus() == 1) { echo "selected='selected'"; } else { echo ""; } ?>>Ativo</option>
						<option value="2" <?php if ($objeto->getUsuarioStatus() == 2) { echo "selected='selected'"; } else { echo ""; } ?>>Inativo</option>
					</select>
					
					<br />
					<label for="idPerfil">Perfil:</label>
					<?php 
						 include_once 'controllers/SelectorController.php';
						 $seletor = new SeletorController();
						 echo $seletor->seletores(3,$objeto->getIdPerfil());
					?>

					<div id="botoesManter">
						<input type='hidden' name='controle' value='Usuario'>
						<input type='hidden' name='acao' value='manter'>
						<input type='hidden' name='id' value='<?php echo $objeto->getPkUsuario()?>'>
						
						<a href="?controle=Usuario&acao=listar">Cancelar</a>&nbsp;&nbsp;
						<button type='submit' id="btSalvar" class='btSalvar'>Salvar</button>
					</div>
				</form>
			</div>
	</article>
</body>
</html>