<?php
$v_params = $this->getParams();
$objeto = $v_params['objeto'];

include_once 'includes/head.php';
?>
</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
	<?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Dados de Acesso</h1>
        <?php if (isset($_GET['msg']) != "") { ?>
		     <div id="mensagem" style="display:block;">
		        <?php 
		        		include_once 'lib/Mensagens.php';
					$msg = new Mensagens($_GET['msg']);
		        ?>
		     </div>
		<?php } ?>
			
			<div id="formulario">
				
				<form method="post">
					
					<label for="id">Id:</label>
					<input type="text" name="id" size="5" id="id" value="<?php echo $objeto->getPkUsuario()?>" disabled="disabled" />
					
					<label for="perfil">Nome:</label>
					<input type="text" name="nome" id="nome" value="<?php echo $objeto->getNome()?>" required />

					<br />
					<label for="cargo">Cargo:</label>
					<input type="text" name="cargo" id="cargo" value="<?php echo $objeto->getCargo()?>" required />
					
					<br />
					<label for="telefone">Telefone:</label>
					<input type="text" name="telefone" id="telefone" value="<?php echo $objeto->getTelefone()?>" required />
					
					<br />
					<label for="email">E-mail:</label>
					<input type="text" name="email" id="email" value="<?php echo $objeto->getEmail()?>" required />
					
					<br />
					<label for="login">Login:</label>
					<input type="text" name="login" id="login" value="<?php echo $objeto->getLogin()?>" required />
					
					<br />
					<label for="senha">Senha:</label>
					<input type="password" name="senha" id="senha" value="<?php echo $objeto->getSenha()?>" required />
					
					<br />
					<label for="cpf">Cpf:</label>
					<input type="text" name="cpf" id="cpf" value="<?php echo $objeto->getCpf()?>" required />
					
					<label for="status">Status:</label>
					<input type="text" name="status" id="status" disabled="disabled" value="<?php if ($objeto->getUsuarioStatus() == 1) { echo "Ativo"; } else if ($objeto->getUsuarioStatus() == 0) { echo "Inativo"; } ?>" required />
					
					<br />
					<label for="idPerfil">Perfil:</label>
					<input type="text" name="perfil" id="perfil" disabled="disabled" value="<?php echo $objeto->getNomePerfil()?>" />
					<input type="hidden" name="idPerfil" id="idPerfil" value="<?php echo $objeto->getIdPerfil()?>" />

					<div id="botoesManter">
						<input type='hidden' name='controle' value='DadosAcesso'>
						<input type='hidden' name='acao' value='manter'>
						<input type='hidden' name='id' value='<?php echo $objeto->getPkUsuario()?>'>
						
						<a href="?controle=Inicio&acao=dashboard">Cancelar</a>&nbsp;&nbsp;
						<button type='submit' class='btSalvar'>Salvar</button>
					</div>
				</form>
			</div>
	</article>
</body>
</html>