<?php
$v_params = $this->getParams();
$objeto = $v_params['objeto'];

include_once 'includes/head.php';
?>
</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
	<?php include_once 'includes/lateral.php'; ?>
    
	<article>
        <h1>Cidade</h1>
        <?php if (isset($_GET['msg']) != "") { ?>
		     <div id="mensagem" style="display:block;">
		        <?php 
		        		include_once 'lib/Mensagens.php';
					$msg = new Mensagens($_GET['msg']);
		        ?>
		     </div>
		<?php } ?>
			
			<div id="formulario">
				
				<form method="post">
					
					<label for="id">Id:</label>
					<input type="text" name="id" size="5" id="id" value="<?php echo $objeto->getPkCidade()?>" disabled="disabled" />
					
					<label for="cidade">Cidade:</label>
					<input type="text" name="cidade" id="cidade" value="<?php echo $objeto->getCidade()?>" required />

					<br />
					<label for="idEstado">Estado:</label>
					<?php  
						 include_once 'controllers/SelectorController.php';
						 $seletor = new SeletorController();
						 echo $seletor->seletores(2,$objeto->getPkEstado());
					?>

					<div id="botoesManter">
						<input type='hidden' name='controle' value='Cidade'>
						<input type='hidden' name='acao' value='manter'>
						<input type='hidden' name='id' value='<?php echo $objeto->getPkCidade()?>'>
						
						<a href="?controle=Cidade&acao=listar">Cancelar</a>&nbsp;&nbsp;
						<button type='submit' class='btSalvar'>Salvar</button>
					</div>
				</form>
				
			</div>
	</article>
</body>
</html>