<?php
$v_params = $this->getParams();
$vetor = $v_params['vetor'];

$controle = $_REQUEST['controle'];

include_once 'includes/head.php';
?>

</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
	<?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Itens de Menu</h1>
        <?php if (isset($_GET['msg']) != "") { ?>
		     <div id="mensagem" style="display:block;">
		        <?php //echo strtoupper($mensagem);
		        		include_once 'lib/Mensagens.php';
					$msg = new Mensagens($_GET['msg']);
		        ?>
		     </div>
		<?php } ?>
		
        <section id="opcoes">
            <div id="filtros">
                <form name="filtro" method="post">
                    <label for="menu">Menu:</label>
                    <input type="text" name="menu" id="menu" value="" />
                    
                    <input type='hidden' name='controle' value='Menu'>
				<input type='hidden' name='acao' value='listar'>
                    <input type="submit" value="Filtrar" />
                </form>
            </div>
            <?php if ($_SESSION['adicionar'] == 1) { ?>
                <a id="novo" href='?controle=<?php echo $controle; ?>&acao=manter' class='icoNovo'>Adicionar um novo item</a>
            <?php } ?>
        </section>
        <div class="clear"></div>
			
			
        <table style="width:100%;" id="table" class="sortable">
			<thead>	
				<tr>
					<th>Id</th>
					<th>Menu</th>
					<th>URL</th>
					<th>Ativo</th>
					<th>Ordem</th>
					<th>Menu pai</th>
					<th class="nosort"></th>				
				</tr>
			</thead>
			<tbody>
				<?php
				 foreach($vetor AS $item) { ?>
					<tr>
						<td><?php echo $item->getPkMenu(); ?></td>
						<td><?php echo $item->getMenu(); ?></td>
						<td><?php echo $item->getUrl(); ?></td>
						<td><?php echo $item->getMenuAtivo(); ?></td>
						<td><?php echo $item->getOrdem(); ?></td>
						<td><?php echo $item->getMenuPai(); ?></td>
						<td>
                            		<?php if ($item->getMenuAtivo() == 0) { ?>
                            			<a href="#" class="icoPublicar linkOpcoes">Publicar</a>
                            		<?php } elseif ($item->getMenuAtivo() == 1) { ?>
                            			<a href="#" class="icoDespublicar linkOpcoes">Despublicar</a>
                            		<?php } ?>
							
							<?php if ($_SESSION['editar'] == 1) { ?>
								<a href='?controle=<?php echo $controle; ?>&acao=manter&id=<?php echo $item->getPkMenu()?>' class='icoEditar linkOpcoes'>Editar</a>
							<?php } ?>
							<?php if ($_SESSION['excluir'] == 1) { ?>
								<a href='?controle=<?php echo $controle; ?>&acao=apagar&id=<?php echo $item->getPkMenu()?>' class='icoExcluir linkOpcoes'>Excluir</a>
							<?php } ?>
						</td>
					</tr>
			<?php } ?>
			</tbody>
        </table>
        <?php // Paginação
        include_once 'includes/paginacao.php'; ?>
	</article>
</body>
</html>