<?php
$v_params = $this->getParams();
$vetor = $v_params['vetor'];

$controle = $_REQUEST['controle'];

include_once 'includes/head.php';
?>

</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
	<?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Menus do Perfil</h1>
        <?php if (isset($_GET['msg']) != "") { ?>
		     <div id="mensagem" style="display:block;">
		        <?php //echo strtoupper($mensagem);
		        		include_once 'lib/Mensagens.php';
					$msg = new Mensagens($_GET['msg']);
		        ?>
		     </div>
		<?php } ?>
		
        <section id="opcoes">
            <div id="filtros">
                <form name="filtro" method="post">
                    <label for="perfil">Perfil:</label>
                    <input type="text" name="perfil" id="perfil" value="" />
                    
                    <label for="menu">Menu:</label>
                    <input type="text" name="menu" id="menu" value="" />
                    
                    <select name="status" id="status">
                        <option value="1" selected="selected">Status do menu:</option>
                        <option value="1">Ativo</option>
                        <option value="2">Inativo</option>
                    </select>
                    
                    <input type='hidden' name='controle' value='PerfilMenu'>
				<input type='hidden' name='acao' value='listar'>
                    <input type="submit" value="Filtrar" />
                </form>
            </div>
            <?php if ($_SESSION['adicionar'] == 1) { ?>
                <a id="novo" href='?controle=<?php echo $controle; ?>&acao=manter' class='icoNovo'>Adicionar um novo perfil</a>
            <?php } ?>
        </section>
        <div class="clear"></div>
			
			
        <table style="width:100%;" id="table" class="sortable">
			<thead>	
				<tr>
					<th>Id</th>
					<th>Perfil</th>
					<th>Menu</th>
					<th class="nosort"></th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach($vetor AS $item) { ?>
					<tr>
						<td><?php echo $item->getPkPerfilMenu(); ?></td>
						<td><?php echo $item->getNomedoPerfil(); ?></td>
						<td><?php echo $item->getNomedoMenu(); ?></td>
						<td>
                            <a href="#" class="icoPublicar linkOpcoes">Publicar</a>
                            <a href="#" class="icoDespublicar linkOpcoes">Despublicar</a>
							<?php if ($_SESSION['editar'] == 1) { ?><a href='?controle=<?php echo $controle; ?>&acao=manter&id=<?php echo $item->getPkPerfilMenu()?>' class='icoEditar linkOpcoes'>Editar</a><?php } ?>
							<?php if ($_SESSION['excluir'] == 1) { ?><a href='?controle=<?php echo $controle; ?>&acao=apagar&id=<?php echo $item->getPkPerfilMenu()?>' class='icoExcluir linkOpcoes'>Excluir</a><?php } ?>
						</td>
						
					</tr>
				<?php } ?>
			</tbody>
		</table>
		<!-- Paginação -->
		<?php include_once 'includes/paginacao.php'; ?>
	</article>
</body>
</html>