<?php
$v_params = $this->getParams();
$vetor = $v_params['vetor'];

include_once 'includes/head.php';
?>

</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
    <?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Suporte T&eacute;cnico</h1>
        
        <section id="opcoes">
            
            <div id="filtros">
                Prezado cliente.<br /><br />Para que possamos atendê-lo com qualidade e rapidez, pedimos que, ao encontrar qualquer problema<br />ou dificuldade no uso deste sistema, entre em contato conosco através do nosso HelpDesk:<br /><br />
                <a href="http://alkantara.com.br/helpdesk/sistema/clientarea.php" title="Suporte Alkantára" target="_blank"><img src="views/includes/images/btn_suporte_akt.png" alt="Suporte Alkantára" /><br />Clique aqui para abrir um novo chamado</a>.
                
            </div>

        </section>
        
	</article>
</body>
</html>