<?php
$v_params = $this->getParams();
$objeto = $v_params['objeto'];

include_once 'includes/head.php';
?>
</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
	<?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Suporte</h1>
        <?php if (isset($_GET['msg']) != "") { ?>
		     <div id="mensagem" style="display:block;">
		        <?php 
		        		include_once 'lib/Mensagens.php';
					$msg = new Mensagens($_GET['msg']);
		        ?>
		     </div>
		<?php } ?>
			
			<div id="formulario">
				
				<form method="post" enctype="multipart/form-data">

					<label for="perfil">Nome:</label>
					<input type="text" name="nome" id="nome" value="<?php echo $_SESSION['nomeUsuario']; ?>" />
					
					<br />
					<label for="telefone">Telefone:</label>
					<input type="text" name="telefone" id="telefone" value="<?php echo $_SESSION['telefone']; ?>" />
					
					<br />
					<label for="email">E-mail:</label>
					<input type="text" name="email" id="email" value="<?php echo $_SESSION['email']; ?>" />
					
					<br />
					<label for="filial"></label>
					<input type="text" name="exibefilial" id="exibefilial" value="<?php echo $_SESSION['filial']; ?>" disabled="disabled" />
					<input type="hidden" name="filial" id="filial" value="<?php echo $_SESSION['filial']; ?>" />
					
					<br />
					<label for="anexo">Anexo:</label>
					<input type="file" name="anexo" id="anexo" value="" />

					<div id="botoesManter">
						<input type='hidden' name='controle' value='Suporte' />
						<input type='hidden' name='acao' value='enviar' />
						<input type="hidden" name="MAX_FILE_SIZE" value="100000000" />
						<!-- <input type='hidden' name='id' value='<?php echo $objeto->getPkUsuario()?>' /> -->
						
						<a href="?controle=Inicio&acao=dashboard">Cancelar</a>&nbsp;&nbsp;
						<button type='submit' class='btSalvar'>Salvar</button>
					</div>
				</form>
			</div>
	</article>
</body>
</html>