<?php
$v_params = $this->getParams();
$vetor = $v_params['vetor'];

$controle = $_REQUEST['controle'];

include_once 'includes/head.php';
?>

</head>
<body>
	<?php include_once 'includes/topo.php'; ?>
	<?php include_once 'includes/lateral.php'; ?>
	
	<article>
        <h1>Usu&aacute;rios</h1>
        <?php if (isset($_GET['msg']) != "") { ?>
		     <div id="mensagem" style="display:block;">
		        <?php //echo strtoupper($mensagem);
		        		include_once 'lib/Mensagens.php';
					$msg = new Mensagens($_GET['msg']);
		        ?>
		     </div>
		<?php } ?>
		
        <section id="opcoes">
            <div id="filtros">
                <form name="filtro" method="post">
                    <label for="nome">Nome:</label>
                    <input type="text" name="nome" id="nome" value="" />
                    
                   <?php
					 // seletor de filiais
					 if ($_SESSION['hashid'] == "superadmin" || $_SESSION['hashid'] == "desenvolvedor") {
					 	include_once 'controllers/SelectorController.php';
					 	$seletor = new SeletorController();
					 	echo $seletor->seletores(14,null);
				?>
		                    <select name="status" id="status">
		                        <option value="0">Status:</option>
		                        <option value="1">Ativo</option>
		                        <option value="2">Inativo</option>
		                    </select>
                    <?php } ?>
                    
                    <input type='hidden' name='controle' value='Usuario'>
				<input type='hidden' name='acao' value='listar'>
                    <input type="submit" value="Filtrar" />
                </form>
            </div>
            <a id="novo" href='?controle=<?php echo $controle; ?>&acao=manter' class='icoNovo'>Adicionar um novo usuário</a>
        </section>
        <div class="clear"></div>
			
			
        <table style="width:100%;" id="table" class="sortable">
			<thead>	
				<tr>
					<th>Id</th>
					<th>Nome</th>
					<th>Cargo</th>
					<th>Telefone</th>
					<th>E-mail</th>
					<th>Perfil de Acesso</th>
				<?php if ($_SESSION['hashid'] == "superadmin" || $_SESSION['hashid'] == "desenvolvedor") { ?>
					<th class="nosort"></th>
				<?php } ?>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach($vetor AS $item) { ?>
					<tr>
						<td><?php echo $item->getPkUsuario(); ?></td>
						<td><?php echo $item->getNome(); ?></td>
						<td><?php echo $item->getCargo(); ?></td>
						<td><?php echo $item->getTelefone(); ?></td>
						<td><?php echo $item->getEmail(); ?></td>
						<td><?php echo $item->getNomePerfil(); ?></td>
					<?php if ($_SESSION['hashid'] == "superadmin" || $_SESSION['hashid'] == "desenvolvedor") { ?>
						<td>
                         <?php if ($item->getUsuarioStatus() == 0) { ?>
                            		<a href="#" class="icoPublicar linkOpcoes">Publicar</a>
                         <?php } else if ($item->getUsuarioStatus() == 1) { ?>
                            		<a href="#" class="icoDespublicar linkOpcoes">Despublicar</a>
                         <?php } ?>
                         
						<?php if ($_SESSION['editar'] == 1) { ?>
							<a href='?controle=<?php echo $controle; ?>&acao=manter&id=<?php echo $item->getPkUsuario()?>' class='icoEditar linkOpcoes'>Editar</a>
						<?php } 
							if ($_SESSION['excluir'] == 1) { ?>
							<a href='?controle=<?php echo $controle; ?>&acao=apagar&id=<?php echo $item->getPkUsuario()?>' class='icoExcluir linkOpcoes'>Excluir</a>
						<?php } ?>
						</td>
					<?php } ?>
					</tr>
				<?php } ?>
			</tbody>
		</table>
		<!-- Paginação -->
		<?php include_once 'includes/paginacao.php'; ?>
	</article>
</body>
</html>